set nocompatible
set shellslash
set runtimepath^=~/.vim

let mapleader=' '

set backspace=indent,eol,start
set history=50
set ruler
set showcmd
set incsearch
set encoding=utf-8
set guioptions=a
set linespace=1
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab
set mouse=a
set novisualbell
set vb t_vb=
set noerrorbells

set langmap=ΑA,ΒB,ΨC,ΔD,ΕE,ΦF,ΓG,ΗH,ΙI,ΞJ,ΚK,ΛL,ΜM,ΝN,ΟO,ΠP,ΡR,ΣS,ΤT,ΘU,ΩV,ΧX,ΖY,ΥZ,αa,βb,ψc,δd,εe,φf,γg,ηh,ιi,ξj,κk,λl,μm,νn,οo,πp,qq,ρr,σs,τt,θu,ωv,ςw,χx,ζz,υy

set autochdir
set number "relativenumber
set hidden
set ignorecase
set smartcase
set tagcase=match
set ai nocin nosi inde=-1
set foldlevelstart=16

set clipboard=unnamed

set wildignore=*.class,*.o,*.meta,*.dll,*.pdb,*.exe,*.asset,*.unity,*.prefab,*.min.js,*.min.css,tags,node_modules,bin,obj,build,dist

set tags=tags;

filetype off

set background=light
if $BACKGROUND == 'dark'
    set background=dark
endif

colorscheme cyan

let g:no_plugin_maps = 1

call plug#begin('~/.vim/plugged')
Plug 'easymotion/vim-easymotion'
Plug 'w0rp/ale'
Plug 'pangloss/vim-javascript'
Plug 'scrooloose/nerdtree'
Plug 'sbl/scvim'
Plug 'digitaltoad/vim-jade'
Plug 'plasticboy/vim-markdown'
Plug 'mxw/vim-jsx'
Plug 'tpope/vim-fugitive'
Plug 'gregsexton/gitv'
Plug 'elzr/vim-json'
Plug 'kien/ctrlp.vim'
Plug 'vim-scripts/javacomplete'
Plug 'christoomey/vim-tmux-navigator'
Plug 'fidian/hexmode'
Plug 'tpope/vim-vinegar'
Plug 'groenewege/vim-less'
Plug 'fatih/vim-go'
Plug 'editorconfig/editorconfig-vim'
Plug 'Chiel92/vim-autoformat'
Plug 'gerw/vim-HiLinkTrace'
Plug 'tfnico/vim-gradle'
Plug 'rbgrouleff/bclose.vim'
Plug 'prettier/vim-prettier'
Plug 'tpope/vim-dispatch'
Plug 'ryanoasis/vim-devicons'
Plug 'tpope/vim-speeddating'
Plug 'vim-scripts/SyntaxRange'
Plug 'jceb/vim-orgmode'
Plug 'mileszs/ack.vim'
Plug 'airblade/vim-rooter'
Plug 'ludovicchabant/vim-gutentags'
Plug 'jkerian/HiCursorWords'
Plug 'vim-scripts/indentpython.vim'
Plug 'nvie/vim-flake8'
if has("gui_running")
    Plug 'bling/vim-airline'
endif
call plug#end()

if &t_Co > 2 || has("gui_running")
    syntax on
    set hlsearch
    set noshellslash
    set laststatus=2
    if has('win32')
        set shell=cmd
        set shellcmdflag=/c
        set shellxquote=\"
    endif
endif

if !has("gui_running")
    let loaded_matchparen = 1
endif


filetype plugin indent on

command! -nargs=0 FormatJSON %!python -m json.tool
command! -nargs=0 FormatHTML %!tidy -q -i --show-errors 0
command! -nargs=0 FormatXML  %!tidy -q -i --show-errors 0 -xml

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

set omnifunc=syntaxcomplete#Complete

let c_space_errors = 1
let java_space_errors = 1
let ruby_space_errors = 1
let javascript_space_errors = 1

let g:jsx_ext_required = 0
let g:tagbar_expand = 0
let g:tagbar_width = 34
let g:tagbar_sort = 0
let Tlist_Use_Right_Window = 1
let Tlist_Enable_Fold_Column = 0
let Tlist_Inc_Winwidth = 0
let g:solarized_termstrans = 1
let g:vim_markdown_folding_disabled = 1
let g:extradite_resize = 0
let g:vim_json_syntax_conceal = 0
let g:ctrlp_cmd = 'CtrlPMixed'
let g:ctrlp_working_path_mode = 'ra'
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#sources#syntax#min_keyword_length = 3
let g:airline_powerline_fonts=1
let g:HiCursorWords_delay = 333
let g:HiCursorWords_hiGroupRegexp = ''
let g:HiCursorWords_debugEchoHiName = 0
let g:HiCursorWords_linkStyle = 'VisualNOS'
let g:NERDTreeHijackNetrw = 0
let g:NERDTreeAutoCenter = 0
let g:NERDTreeHighlightCursorline = 1
let g:formatprg_args_c = "--style=java"
let g:formatprg_args_cpp = "--style=java"
let g:formatprg_args_expr_javascript = '"-a -f - -".(&expandtab ? "s ".&shiftwidth : "t").(&textwidth ? " -w ".&textwidth : "")'
let g:EditorConfig_core_mode = 'python_external'
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
let g:Gitv_TruncateCommitSubjects = 1
let g:Gitv_DoNotMapCtrlKey = 1
let g:rooter_manual_only = 1
let g:rooter_patterns = ['.git', '.gitignore', '.git/', '.svn/']
let g:gutentags_project_root = ['.gitignore', '.git', '.hg', '.bzr', '_darcs', '_darcs', '_FOSSIL_', '.fslckout']
let g:gutentags_cache_dir = '~/.cache/tags'
let g:ale_lint_on_text_changed = 'never'
let g:ale_set_highlights = 0

let &t_ZH="\e[3m"
let &t_ZR="\e[23m"

map <leader><Tab>n :tabe<cr>
map <leader><Tab>d :tabclose<cr>
map <leader><Tab>[ :tabprevious<cr>
map <leader><Tab>p :tabprevious<cr>
map <leader><Tab>] :tabnext<cr>
map <leader><Tab>n :tabnext<cr>

map <leader>op :NERDTreeToggle<cr>
map <leader>oP :NERDTreeFind<cr>

map <leader>bb :CtrlPBuffer<cr>
map <leader>b, :CtrlPBuffer<cr>
map <leader>b] :bnext<cr>
map <leader>bn :bnext<cr>
map <leader>b[ :bprevious<cr>
map <leader>bp :bprevious<cr>
map <leader>bk :Bclose<cr>
map <leader>bN :vnew<cr>
map <leader>< :CtrlPBuffer<cr>

map <leader>cd :CtrlPTag<cr><c-\>w

map <leader>w <c-w>
map <c-Tab> <c-w>w
map <leader>f/ :CtrlP<cr>
map <leader>p/ :CtrlP<cr>
map <leader><leader> :CtrlP<cr>
map <leader>/p :Ack! <c-r>=expand("<cword>")<cr> <c-r>=FindRootDirectory()<cr><c-b><s-right><s-right>
map <leader>/d :Ack! <c-r>=expand("<cword>")<cr> <c-r>=FindRootDirectory()<cr><c-b><s-right><s-right>
map <leader>]e :lnext<cr>
map <leader>[e :lprevious<cr>

map ; <Plug>(easymotion-prefix)
map , <Plug>(easymotion-prefix)

map <down> gj
map <up> gk
imap <down> <c-o>gj
imap <up> <c-o>gk
imap <insert> <esc>"*P']ji

cnoremap <c-g> <c-[>
tnoremap <Esc><Esc> <c-\><c-n>

autocmd FileType vim setlocal keywordprg=:help
autocmd FileType python setlocal keywordprg=pydoc
